routes/web.php
<?php
use App\Http\Controllers\CommentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/blog-detail/{id}', [HomeController::class, 'blogdetail'])->name('blogdetail');
Route::post('/comment', [CommentController::class, 'store'])->name('comment.store');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::resource('blog', BlogController::class);

Route::fallback(function(){
    return "shilpa page 404 page";
});


require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;

class Blog extends Model
{
    use HasFactory, softDeletes;
    protected $fillable = [
        'title',
        'description',
        'photo_src',
        'status',
        'category_id',
        'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'blog_tags', 'blog_id', 'tag_id');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\BlogTags;
use App\Models\Category;
use App\Models\Tag;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //$blogs = Blog::all();
        $blogs = Blog::paginate(2);
        return view('blogs.index', compact('blogs'));
    }

    /**
     *  creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();

        /*
        if (count($categories)==0){
            $cate = Category::create([
                'title' => 'Food',
            ]);

            $cate = Category::create([
                'title' => 'Beauty',
            ]);

            $cate = Category::create([
                'title' => 'Test 1',
            ]);

            $cate = Category::create([
                'title' => 'Test 2',
            ]);

            $categories = Category::all();
        }

        if (count($tags)==0){
            $cate = Tag::create([
                'name' => 'Trending',
            ]);

            $cate = Tag::create([
                'name' => 'Life Style',
            ]);

            $cate = Tag::create([
                'name' => 'Healthy Food',
            ]);

            $cate = Tag::create([
                'name' => 'Cooking',
            ]);

            $tags = Tag::all();
        }
        */

        $blog = [];
        $action = "Add";
        return view('blogs.createedit', compact('blog','categories', 'tags', 'action'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // add validation
        $request->validate([
            'title' => 'required|max:100',
            'description' => 'required',
            'photo_src' => ['required', 'min:10', 'max:5000', 'mimes:png,jpg,gif'],
            'category_id' => 'required',
            //'tag_id' => 'required',
        ]);

        $fileName = time().'_'.$request->photo_src->getClientOriginalName();
        $data = $request->except('photo_src');
        $data['photo_src'] = $request->photo_src->storeAs('/blog', $fileName);

        $blog = Blog::create($data);
        $blog->tags()->attach($request->tag_id);
        return redirect(route('blog.index'))->with('notification', 'New Blog created successfully.!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        return view('blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        $action = "Update";
        $categories = Category::all();
        $tags = Tag::all();


        return view('blogs.createedit', compact('blog', 'categories', 'tags', 'action'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Blog $blog)
    {
        // add validation
        if (isset($request->photo_src)) {
            $request->validate([
                'title' => 'required|max:100',
                'description' => 'required',
                'photo_src' => ['required', 'min:10', 'max:5000', 'mimes:png,jpg,gif'],
                'category_id' => 'required',
                //'tag_id' => 'required',
            ]);
        } else {
            $request->validate([
                'title' => 'required|max:100',
                'description' => 'required',
                'category_id' => 'required',
                //'tag_id' => 'required',
            ]);
        }

        $data = $request->except('photo_src');

        if (isset($request->photo_src)) {
            $fileName = time().'_'.$request->photo_src->getClientOriginalName();
            $data['photo_src'] = $request->photo_src->storeAs('/blog', $fileName);

            Storage::disk('public')->delete([$blog->photo_src]);
        }

        BlogTags::where('blog_id', '=', $blog->id)->delete();

        $blog->update($data);
        $blog->tags()->attach($request->tag_id);

        return redirect(route('blog.index'))->with('notification', 'Blog updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        $blog->delete();
        return redirect(route('blog.index'))->with('delnotification', 'Blog Title ::-' . $blog->title .  ' deleted successfully!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/blogs/createedit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Blog Data') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="container">
                        {{-- @if ($errors->any())
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger" role="alert">
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif --}}
                        <div class="row">
                            <div class="col-12">
                                <h1 class="mt-3 mb-3 float-left"><b>Blog {{$action}}</b></h1>
                                <a class="mt-3 mb-3 float-right btn btn-primary" href="{{ route('blog.index')}}" role="button">Back</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <form action="{{ ($action=="Add") ? route('blog.store') : route('blog.update', [$blog->id]) }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @if ($action=='Update')
                                        @method('patch')
                                    @endif
                                    <div class="form-group">
                                        <label for="">Title</label>
                                        <input value="{{isset($blog->title) ? $blog->title : ''}}" type="text" class="form-control" name="title" placeholder="Blog Title">
                                        <input value="{{Auth::user()->id}}" type="hidden" name="user_id">
                                    </div>
                                    @if($errors->has('title'))
                                        <div class="alert alert-danger" role="alert">{{ $errors->first('title') }}</div>
                                    @endif
                                    <div class="form-group">
                                        <label for="">Description</label>
                                        <textarea class="form-control" name="description" rows="3">{{isset($blog->description) ? $blog->description : ''}}</textarea>
                                    </div>
                                    @if($errors->has('description'))
                                        <div class="alert alert-danger" role="alert">{{ $errors->first('description') }}</div>
                                    @endif
                                    <div class="form-group">
                                        <label for="">Blog Photo</label>
                                        <input type="file" class="form-control-file" name="photo_src">
                                        @if (isset($blog->photo_src))
                                            <img class="mt-3" width="20%" src="{{asset('/storage/'.$blog->photo_src)}}" />
                                        @else
                                        @endif
                                    </div>
                                    @if($errors->has('photo_src'))
                                        <div class="alert alert-danger" role="alert">{{ $errors->first('photo_src') }}</div>
                                    @endif
                                    <div class="form-group">
                                        <label for="">Category</label>
                                        <select class="form-control" name="category_id">
                                            <option value="">Select Category</option>
                                            @foreach ($categories as $item)
                                            <option {{(isset($blog->category_id) && $blog->category_id==$item->id) ? 'selected' : ''}} value="{{$item->id}}">{{$item->title}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if($errors->has('category_id'))
                                        <div class="alert alert-danger" role="alert">{{ $errors->first('category_id') }}</div>
                                    @endif
                                    <div class="form-group">
                                        <label for="">Tag</label>
                                        <select multiple class="form-control" name="tag_id[]">
                                            @foreach ($tags as $item)
                                            <option {{(isset($blog->tags) ? (in_array($item->id, $blog->tags->pluck('pivot')->pluck('tag_id')->toArray()) ? "selected": "") : '')}} value="{{$item->id}}">{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if($errors->has('tag_id'))
                                        <div class="alert alert-danger" role="alert">{{ $errors->first('tag_id') }}</div>
                                    @endif
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/blogs/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Blog Data') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                @if (session('notification'))
                                    <!-- Success Alert -->
                                    <div class="alert alert-success alert-dismissible fade show">
                                        <strong>Success!</strong> {{ session('notification') }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                    </div>
                                @endif
                                @if (session('delnotification'))
                                    <!-- Error Alert -->
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        <strong>Delete!</strong> {{ session('delnotification') }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                    </div>
                                @endif
                                <h1 class="mt-3 mb-3 float-left"><b>Blog Listing</b></h1>
                                <a class="mt-3 mb-3 float-right btn btn-primary" href="{{ route('blog.create')}}" role="button">Create</a>
                                @if ($blogs)
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Photo</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Category</th>
                                        <th scope="col">User</th>
                                        <th scope="col">Action</th>
                                        </tr>
                                    </thead>

                                    @foreach ($blogs as $item)
                                        <tbody>
                                            <tr>
                                            <th scope="row">{{ $loop->iteration }}</th>
                                            <td width="15%">
                                                <img src="{{asset('/storage/'.$item->photo_src)}}" />
                                            </td>
                                            <td>{{$item->title}}</td>
                                            <td>{{$item->category->title}}</td>
                                            <td>{{$item->user->name}}</td>
                                            <td>
                                                <a class="btn btn-info" href="{{ route('blog.show', $item)}}" role="button">Show</a>

                                                <a class="btn btn-info" href="{{ route('blog.edit', $item->id)}}" role="button">Edit</a>

                                                <form action="{{ route('blog.destroy', $item->id)}}" method="POST">
                                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                                    @csrf @method('DELETE')
                                                </form>
                                            </td>
                                            </tr>
                                        </tbody>
                                    @endforeach

                                    {{$blogs->links()}}

                                    @if($blogs->isEmpty())
                                    <tr>
                                        <td colspan="10">
                                            <div class="flex flex-col justify-center items-center py-4 text-lg">
                                                {{ __('No Result Found') }}
                                            </div>
                                        </td>
                                    </tr>
                                    @endif
                                </table>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/blogs/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Blog Data') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <h1 class="mt-3 mb-3 float-left"><b>Blog Add</b></h1>
                                <a class="mt-3 mb-3 float-right btn btn-primary" href="{{ route('blog.index')}}" role="button">Back</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <strong>Title: </strong>
                                    {{$blog->title}}
                                </div>

                                <div class="form-group">
                                    <strong>Description: </strong>
                                    {{$blog->description}}
                                </div>

                                <div class="form-group">
                                    <strong>Blog Photo: </strong>
                                    <img width="20%" src="{{asset('/storage/'.$blog->photo_src)}}" />
                                </div>

                                <div class="form-group">
                                    <strong>Category: </strong>
                                    {{$blog->category->title}}
                                </div>

                                <div class="form-group">
                                    <strong>Tag: </strong>
                                    {{ str_replace(['"', '[', ']'], [' ', '', ''], $blog->tags->pluck('name'))}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>